Repository MemorAIzee/MemorAIzee-BackEnd, pull requests merged in 2024-05, with the labels that each got.

#29 🐛 FIX. CORS 오류 수정
  src/main/java/memoraize/global/security/config/SecurityConfig.java
  src/main/java/memoraize/global/security/jwt/handler/JwtLoginFailureHandler.java
  src/main/java/memoraize/global/security/jwt/handler/JwtLoginSuccessHandler.java
Labels: :bug: bug

#32 ✨ FEAT. 팔로잉 CRUD 기능 구현
  src/main/java/memoraize/domain/album/repository/AlbumPostRepository.java
  src/main/java/memoraize/domain/album/service/AlbumPostQueryService.java
  src/main/java/memoraize/domain/album/service/AlbumPostQueryServiceImpl.java
  src/main/java/memoraize/domain/album/web/dto/AlbumPostRequestDTO.java
  src/main/java/memoraize/domain/review/entity/Review.java
  src/main/java/memoraize/domain/review/service/ReviewCommandService.java
  src/main/java/memoraize/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/memoraize/domain/review/web/controller/ReviewRestController.java
  src/main/java/memoraize/domain/user/converter/UserConverter.java
  src/main/java/memoraize/domain/user/entity/User.java
  src/main/java/memoraize/domain/user/entity/mapping/Follow.java
  src/main/java/memoraize/domain/user/exception/UserNotExistException.java
  src/main/java/memoraize/domain/user/repository/FollowRepository.java
  src/main/java/memoraize/domain/user/repository/UserRepository.java
  src/main/java/memoraize/domain/user/service/UserCommandService.java
  src/main/java/memoraize/domain/user/service/UserCommandServiceImpl.java
  src/main/java/memoraize/domain/user/service/UserQueryService.java
  src/main/java/memoraize/domain/user/service/UserQueryServiceImpl.java
  src/main/java/memoraize/domain/user/web/controller/UserRestController.java
  src/main/java/memoraize/domain/user/web/dto/UserResponseDTO.java
  src/main/java/memoraize/global/annotation/LoginUser.java
  src/main/java/memoraize/global/config/WebConfig.java
  src/main/java/memoraize/global/enums/statuscode/ErrorStatus.java
  src/main/java/memoraize/global/resolver/LoginUserArgumentResolver.java
  src/main/java/memoraize/global/security/config/SecurityConfig.java
  src/main/java/memoraize/global/security/jwt/handler/JwtLoginFailureHandler.java
  src/main/java/memoraize/global/security/jwt/handler/JwtLoginSuccessHandler.java
Labels: :sparkles: feature

#36 ✨ FEAT. 리뷰 CRUD 기능 구현
  src/main/java/memoraize/domain/album/service/AlbumPostQueryServiceImpl.java
  src/main/java/memoraize/domain/album/web/dto/AlbumPostRequestDTO.java
  src/main/java/memoraize/domain/photo/exception/MetadataNotExistException.java
  src/main/java/memoraize/domain/photo/exception/PhotoNotExistException.java
  src/main/java/memoraize/domain/photo/exception/PlaceNotExistException.java
  src/main/java/memoraize/domain/review/converter/ReviewConverter.java
  src/main/java/memoraize/domain/review/entity/Review.java
  src/main/java/memoraize/domain/review/exception/PageVariableInvalidException.java
  src/main/java/memoraize/domain/review/repository/ReviewRepository.java
  src/main/java/memoraize/domain/review/service/ReviewCommandService.java
  src/main/java/memoraize/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/memoraize/domain/review/service/ReviewQueryService.java
  src/main/java/memoraize/domain/review/service/ReviewQueryServiceImpl.java
  src/main/java/memoraize/domain/review/validation/annotation/Pageable.java
  src/main/java/memoraize/domain/review/validation/validator/PageableConstraint.java
  src/main/java/memoraize/domain/review/web/controller/ReviewRestController.java
  src/main/java/memoraize/domain/review/web/dto/ReviewRequestDTO.java
  src/main/java/memoraize/domain/review/web/dto/ReviewResponseDTO.java
  src/main/java/memoraize/global/enums/statuscode/ErrorStatus.java
Labels: :bug: bug, :sparkles: feature

#37 ✨ FEAT. 특정 사용자 앨범 목록 조회 기능 구현
  src/main/java/memoraize/domain/album/repository/AlbumPostRepository.java
  src/main/java/memoraize/domain/album/service/AlbumPostCommandService.java
  src/main/java/memoraize/domain/album/service/AlbumPostCommandServiceImpl.java
  src/main/java/memoraize/domain/album/service/AlbumPostQueryService.java
  src/main/java/memoraize/domain/album/service/AlbumPostQueryServiceImpl.java
  src/main/java/memoraize/domain/album/web/controller/AlbumPostController.java
  src/main/java/memoraize/domain/album/web/controller/AlbumPostRestController.java
  src/main/java/memoraize/global/enums/statuscode/ErrorStatus.java
Labels: :sparkles: feature

#40 ✨ FEAT. GoogleMapsPlatform, Search 기능 구현
  src/main/java/memoraize/domain/album/repository/AlbumPostRepository.java
  src/main/java/memoraize/domain/album/service/GoogleMapsPlatformService.java
  src/main/java/memoraize/domain/album/service/GoogleMapsPlatformServiceImpl.java
  src/main/java/memoraize/domain/album/web/dto/GoogleMapsPlatformRequestDTO.java
  src/main/java/memoraize/domain/album/web/dto/GoogleMapsPlatformResponseDTO.java
  src/main/java/memoraize/domain/review/repository/PlaceRepository.java
  src/main/java/memoraize/domain/review/repository/ReviewRepository.java
  src/main/java/memoraize/domain/search/service/SearchKeywordService.java
  src/main/java/memoraize/domain/search/service/SearchKeywordServiceImpl.java
  src/main/java/memoraize/domain/search/web/controller/SearchKeywordController.java
  src/main/java/memoraize/domain/search/web/dto/SearchKeywordRequestDTO.java
  src/main/java/memoraize/domain/search/web/dto/SearchKeywordResponseDTO.java
  src/main/java/memoraize/domain/user/repository/UserRepository.java
Labels: :sparkles: feature

#42 ✨ FEAT. 앨범 좋아요 기능 구현
  src/main/java/memoraize/domain/album/converter/AlbumPostConverter.java
  src/main/java/memoraize/domain/album/entity/Album.java
  src/main/java/memoraize/domain/album/entity/mapping/AlbumLiked.java
  src/main/java/memoraize/domain/album/exception/AlbumNotExistException.java
  src/main/java/memoraize/domain/album/repository/AlbumLikedRepository.java
  src/main/java/memoraize/domain/album/repository/AlbumPostRepository.java
  src/main/java/memoraize/domain/album/service/AlbumPostCommandService.java
  src/main/java/memoraize/domain/album/service/AlbumPostCommandServiceImpl.java
  src/main/java/memoraize/domain/album/web/controller/AlbumPostRestController.java
Labels: :sparkles: feature

#49 ✨ FEAT. webhook 요청 응답 추가
  src/main/java/memoraize/domain/slideshow/web/controller/SlideShowRestController.java
  src/main/java/memoraize/domain/slideshow/web/dto/SlideShowRequestDTO.java
Labels: :bug: bug, :sparkles: feature

#50 ✨ FEAT. 슬라이드쇼 생성 API 구현
  build.gradle
  src/main/java/memoraize/domain/album/entity/Album.java
  src/main/java/memoraize/domain/album/service/AlbumPostCommandServiceImpl.java
  src/main/java/memoraize/domain/album/web/dto/AlbumPostRequestDTO.java
  src/main/java/memoraize/domain/slideshow/entity/Memories.java
  src/main/java/memoraize/domain/slideshow/entity/SlideShowChunk.java
  src/main/java/memoraize/domain/slideshow/repository/MemoriesRepository.java
  src/main/java/memoraize/domain/slideshow/repository/SlideShowChunkRepository.java
  src/main/java/memoraize/domain/slideshow/service/SlideShowCommandService.java
  src/main/java/memoraize/domain/slideshow/service/SlideShowCommandServiceImpl.java
  src/main/java/memoraize/domain/slideshow/service/SlideShowQueryService.java
  src/main/java/memoraize/domain/slideshow/service/SlideShowQueryServiceImpl.java
  src/main/java/memoraize/domain/slideshow/web/controller/SlideShowRestController.java
  src/main/java/memoraize/global/aws/s3/AmazonS3Manager.java
  src/main/java/memoraize/global/cloudinary/CloudinaryService.java
  src/main/java/memoraize/global/config/AmazonConfig.java
  src/main/java/memoraize/global/util/BasicAuthHeader.java
  src/main/java/memoraize/global/util/FFmpegService.java
Labels: :sparkles: feature

#52 :sparkles: FEAT. Place에 google place ID 추가
  src/main/java/memoraize/domain/photo/service/PhotoCommandServiceImpl.java
  src/main/java/memoraize/domain/review/converter/PlaceConverter.java
  src/main/java/memoraize/domain/review/entity/Place.java
  src/main/java/memoraize/global/gcp/map/GoogleMapManager.java
  src/main/java/memoraize/global/gcp/map/dto/GooglePlaceApiResponseDTO.java
  src/main/java/memoraize/global/gcp/map/dto/Place.java
  src/test/java/memoraize/gcp/map/GoogleMapManagerTest.java
Labels: :sparkles: feature

#53 ✨ 통합검색 기능, 장소 상세보기 API 구현
  src/main/java/memoraize/domain/album/repository/AlbumPostRepository.java
  src/main/java/memoraize/domain/album/service/GoogleMapsPlatformService.java
  src/main/java/memoraize/domain/album/service/GoogleMapsPlatformServiceImpl.java
  src/main/java/memoraize/domain/album/web/controller/GoogleMapsPlatformController.java
  src/main/java/memoraize/domain/review/repository/PlaceRepository.java
  src/main/java/memoraize/domain/review/repository/ReviewRepository.java
  src/main/java/memoraize/domain/search/service/PlaceDetailPageService.java
  src/main/java/memoraize/domain/search/service/PlaceDetailPageServiceImpl.java
  src/main/java/memoraize/domain/search/service/SearchKeywordService.java
  src/main/java/memoraize/domain/search/service/SearchKeywordServiceImpl.java
  src/main/java/memoraize/domain/search/web/controller/SearchKeywordController.java
  src/main/java/memoraize/domain/search/web/dto/PlaceDetailRequestDto.java
  src/main/java/memoraize/domain/search/web/dto/PlaceDetailResponseDto.java
  src/main/java/memoraize/domain/search/web/dto/SearchKeywordRequestDTO.java
  src/main/java/memoraize/domain/search/web/dto/TotalPlaceDetailPageResponseDto.java
Labels: :sparkles: feature

#57 🎨 CHORE. ResponseDto 형식 전면 수정
  src/main/java/memoraize/domain/album/repository/AlbumPostRepository.java
  src/main/java/memoraize/domain/review/repository/PlaceRepository.java
  src/main/java/memoraize/domain/review/repository/ReviewRepository.java
  src/main/java/memoraize/domain/search/service/SearchKeywordServiceImpl.java
  src/main/java/memoraize/domain/search/web/dto/SearchKeywordResponseDTO.java
  src/main/java/memoraize/domain/user/repository/UserRepository.java
Labels: :bug: bug

#58 :art: CHORE. ResponseDto 형식 전면 수정에 따른 Service code 전면 수정
  src/main/java/memoraize/domain/album/service/GoogleMapsPlatformServiceImpl.java
  src/main/java/memoraize/domain/album/web/dto/GoogleMapsPlatformResponseDTO.java
Labels: :bug: bug

#59 :sparkles: FEAT. search Album 내용에 사용자 이름 추가
  src/main/java/memoraize/domain/search/service/SearchKeywordServiceImpl.java
  src/main/java/memoraize/domain/search/web/dto/SearchKeywordResponseDTO.java
Labels: :sparkles: feature

#60 :sparkles: FEAT. search Album 내용에 대표 이미지 추가
  src/main/java/memoraize/domain/search/service/SearchKeywordServiceImpl.java
  src/main/java/memoraize/domain/search/web/dto/SearchKeywordResponseDTO.java
Labels: :sparkles: feature

#64 🐛 FIX. 각종 오류 해결
  src/main/java/memoraize/domain/album/service/AlbumMapDisplayService.java
  src/main/java/memoraize/domain/photo/service/PhotoCommandServiceImpl.java
  src/main/java/memoraize/domain/review/converter/PlaceConverter.java
  src/main/java/memoraize/domain/review/entity/Place.java
  src/main/java/memoraize/domain/search/service/PlaceDetailPageServiceImpl.java
  src/main/java/memoraize/domain/search/service/SearchKeywordServiceImpl.java
  src/main/java/memoraize/domain/search/web/dto/PlaceDetailResponseDto.java
  src/main/java/memoraize/global/aws/s3/AmazonS3Manager.java
  src/main/java/memoraize/global/gcp/map/GoogleMapManager.java
  src/main/java/memoraize/global/gcp/map/dto/GooglePhotoResponseDto.java
  src/main/java/memoraize/global/gcp/map/dto/Place.java
Labels: :bug: bug, :sparkles: feature

#65 ✨ FEAT. 앨범 생성 비동기 처리
  src/main/java/memoraize/domain/album/service/AlbumPostCommandServiceImpl.java
  src/main/java/memoraize/domain/album/service/GoogleMapsPlatformServiceImpl.java
  src/main/java/memoraize/domain/photo/converter/PhotoConverter.java
  src/main/java/memoraize/domain/photo/entity/Metadata.java
  src/main/java/memoraize/domain/photo/entity/Photo.java
  src/main/java/memoraize/domain/photo/service/GeminiApiServiceImpl.java
  src/main/java/memoraize/domain/photo/service/PhotoCommandService.java
  src/main/java/memoraize/domain/photo/service/PhotoCommandServiceImpl.java
  src/main/java/memoraize/domain/photo/service/VisionApiServiceImpl.java
  src/main/java/memoraize/domain/review/entity/Place.java
  src/main/java/memoraize/domain/review/repository/PlaceRepository.java
  src/main/java/memoraize/global/aws/s3/AmazonS3Manager.java
  src/main/java/memoraize/global/gcp/map/GoogleMapManager.java
Labels: :bug: bug, :sparkles: feature

#68 ✨FEAT. Gemini api 프롬프트 수정
  README.md
  src/main/java/memoraize/domain/photo/service/GeminiApiService.java
  src/main/java/memoraize/domain/photo/service/GeminiApiServiceImpl.java
  src/main/java/memoraize/domain/photo/service/PhotoCommandServiceImpl.java
Labels: :sparkles: feature

#71 ✨ FEAT. 사용자 음성 추가 및 변환 API 구현
  build.gradle
  src/main/java/memoraize/MemorAIzeApplication.java
  src/main/java/memoraize/domain/album/service/AlbumPostCommandServiceImpl.java
  src/main/java/memoraize/domain/album/service/AlbumPostQueryServiceImpl.java
  src/main/java/memoraize/domain/album/service/GoogleMapsPlatformServiceImpl.java
  src/main/java/memoraize/domain/album/web/controller/AlbumPostRestController.java
  src/main/java/memoraize/domain/album/web/controller/GoogleMapsPlatformController.java
  src/main/java/memoraize/domain/photo/converter/PhotoConverter.java
  src/main/java/memoraize/domain/photo/entity/Photo.java
  src/main/java/memoraize/domain/photo/service/GeminiApiServiceImpl.java
  src/main/java/memoraize/domain/photo/service/PhotoCommandServiceImpl.java
  src/main/java/memoraize/domain/photo/service/VisionApiService.java
  src/main/java/memoraize/domain/photo/service/VisionApiServiceImpl.java
  src/main/java/memoraize/domain/photo/web/controller/TestController.java
  src/main/java/memoraize/domain/photo/web/dto/PhotoResponseDTO.java
  src/main/java/memoraize/domain/review/service/ReviewCommandServiceImpl.java
  src/main/java/memoraize/domain/review/web/controller/ReviewRestController.java
  src/main/java/memoraize/domain/slideshow/web/controller/SlideShowRestController.java
  src/main/java/memoraize/domain/user/entity/User.java
  src/main/java/memoraize/domain/user/service/UserCommandServiceImpl.java
  src/main/java/memoraize/domain/user/web/controller/UserRestController.java
  src/main/java/memoraize/domain/voice/converter/VoiceConverter.java
  src/main/java/memoraize/domain/voice/entity/PhotoNarration.java
  src/main/java/memoraize/domain/voice/entity/Voice.java
  src/main/java/memoraize/domain/voice/repository/PhotoNarrationRepository.java
  src/main/java/memoraize/domain/voice/repository/VoiceRepository.java
  src/main/java/memoraize/domain/voice/service/VoiceCommandService.java
  src/main/java/memoraize/domain/voice/service/VoiceCommandServiceImpl.java
  src/main/java/memoraize/domain/voice/web/controller/VoiceRestController.java
  src/main/java/memoraize/domain/voice/web/dto/VoiceRequestDto.java
  src/main/java/memoraize/domain/voice/web/dto/VoiceResponseDto.java
  src/main/java/memoraize/global/aws/s3/AmazonS3Manager.java
  src/main/java/memoraize/global/cloudinary/CloudinaryService.java
  src/main/java/memoraize/global/elevenlabs/ElevenlabsManager.java
  src/main/java/memoraize/global/enums/statuscode/ErrorStatus.java
  src/main/java/memoraize/global/gcp/map/GoogleMapManager.java
  src/main/java/memoraize/global/security/LoginService.java
  src/main/java/memoraize/global/security/jwt/JwtService.java
  src/main/java/memoraize/global/security/jwt/filter/CustomUsernamePwdAuthenticationFilter.java
  src/main/java/memoraize/global/security/jwt/filter/JwtAuthenticationFilter.java
  src/main/java/memoraize/global/security/jwt/handler/JwtLoginFailureHandler.java
  src/main/java/memoraize/global/security/jwt/handler/JwtLoginSuccessHandler.java
  src/main/java/memoraize/global/security/oauth/CustomOAuth2UserService.java
  src/main/java/memoraize/global/security/oauth/handler/OAuth2LoginFailureHandler.java
  src/main/java/memoraize/global/security/oauth/handler/OAuth2LoginSuccessHandler.java
  src/main/java/memoraize/global/util/FFmpegService.java
  src/main/java/memoraize/global/util/FileConverter.java
Labels: :bug: bug, :sparkles: feature

#72 :bug: FIX. 멀티 스레드 동시성 문제 해결
  src/main/java/memoraize/domain/album/service/AlbumPostCommandServiceImpl.java
  src/main/java/memoraize/domain/photo/service/PhotoCommandServiceImpl.java
  src/main/java/memoraize/domain/voice/repository/PhotoNarrationRepository.java
  src/main/java/memoraize/domain/voice/service/VoiceCommandServiceImpl.java
  src/main/java/memoraize/global/config/AsyncConfig.java
Labels: :bug: bug

#73 :bug: FIX. 슬라이드쇼 S3 브라우저 재생 오류 해결
  src/main/java/memoraize/global/util/FFmpegService.java
Labels: :bug: bug

#74 ✨ FEAT. 메인 페이지 슬라이드 쇼 조회 API
  src/main/java/memoraize/domain/photo/service/PhotoCommandServiceImpl.java
  src/main/java/memoraize/domain/slideshow/service/SlideShowQueryService.java
  src/main/java/memoraize/domain/slideshow/service/SlideShowQueryServiceImpl.java
  src/main/java/memoraize/domain/slideshow/web/controller/SlideShowRestController.java
  src/main/java/memoraize/domain/slideshow/web/dto/SlideShowResponseDTO.java
  src/main/java/memoraize/global/cloudinary/CloudinaryService.java
Labels: :bug: bug, :sparkles: feature

#77 :sparkles: FEAT. 메인 페이지 슬라이드 쇼 조회 최신순으로 변경
  src/main/java/memoraize/domain/slideshow/repository/MemoriesRepository.java
  src/main/java/memoraize/domain/slideshow/service/SlideShowQueryServiceImpl.java
  src/main/java/memoraize/domain/slideshow/web/dto/SlideShowResponseDTO.java
Labels: :sparkles: feature
